import { Header } from '@/components/Utils/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Footer } from '@/components/Utils/Footer'

export const metadata: Metadata = {
  title: 'Programa Mulher - Confea/Crea',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
